/**
 *This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.
 */
package com.vg.emp.myauthenticationservice.controller;

import com.vg.emp.myauthenticationservice.MyAuthenticationService;
import java.lang.String;
import javax.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
@RequestMapping(value = "/myAuthentication")
public class MyAuthenticationController {

    @Autowired
    private MyAuthenticationService myAuthenticationService;

    @RequestMapping(value = "/sampleJavaOperation", produces = "application/json", method = RequestMethod.GET)
    public String sampleJavaOperation(@RequestParam(value = "name", required = false) String name, HttpServletRequest request) {
        return myAuthenticationService.sampleJavaOperation(name, request);
    }
}
